
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS total_price INTEGER DEFAULT 0;
ALTER TABLE project_works ADD COLUMN IF NOT EXISTS price INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS expose_on_signup BOOLEAN DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS expose_on_re_reg BOOLEAN DEFAULT true;
