import { useState, useRef, useCallback, useEffect } from 'react';
import LabMode from './LabMode';
import { awardEarTrainingPoints } from '../../lib/gamePoints';
import { useGameStatus, getTodayKey, fmtCountdownDaily } from '../../lib/useGameStatus';
import { useAuth } from '../../contexts/AuthContext';

type ActiveMode = 'training' | 'lab';

const FREQ_MIN = 80;
const FREQ_MAX = 8000;
const ANGLE_MIN = -135;
const ANGLE_MAX = 135;
// Thresholds in octaves — the natural unit for audio/EQ work.
// ±1/8 octave correct  ≈ ±9% frequency ratio  (advanced ear-training standard)
// ±1/3 octave close    ≈ ±26% frequency ratio
const CORRECT_OCTAVES = 1 / 8;
const CLOSE_OCTAVES = 1 / 3;
const CORRECT_RATIO = Math.LN2 * CORRECT_OCTAVES;   // natural-log threshold ≈ 0.0866
const CLOSE_RATIO = Math.LN2 * CLOSE_OCTAVES;        // natural-log threshold ≈ 0.2310
const TOLERANCE_PCT = 8;
const TOTAL_ROUNDS = 10;

function freqToAngle(freq: number): number {
  const t = Math.log(freq / FREQ_MIN) / Math.log(FREQ_MAX / FREQ_MIN);
  return ANGLE_MIN + t * (ANGLE_MAX - ANGLE_MIN);
}

function angleToFreq(angle: number): number {
  const t = Math.min(1, Math.max(0, (angle - ANGLE_MIN) / (ANGLE_MAX - ANGLE_MIN)));
  return Math.round(FREQ_MIN * Math.pow(FREQ_MAX / FREQ_MIN, t));
}

function clamp(v: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, v));
}

function generateTarget(): number {
  const logMin = Math.log(FREQ_MIN);
  const logMax = Math.log(FREQ_MAX);
  return Math.round(Math.exp(logMin + Math.random() * (logMax - logMin)));
}

type GameState = 'playing' | 'result' | 'session_end';
type GameMode = 'easy' | 'hard';
type Proximity = 'far' | 'close';
type Result = 'correct' | 'incorrect';

interface RoundRecord {
  diff: number;
  correct: boolean;
}

function getProximity(selected: number, target: number): Proximity {
  return Math.abs(Math.log(selected / target)) <= CLOSE_RATIO ? 'close' : 'far';
}

function getResult(selected: number, target: number): Result {
  return Math.abs(Math.log(selected / target)) <= CORRECT_RATIO ? 'correct' : 'incorrect';
}

function getKnobShadow(gameState: GameState, result: Result | null, proximity: Proximity, mode: GameMode) {
  const base = 'inset 0 1px 0 rgba(255,255,255,0.06), 0 4px 20px rgba(0,0,0,0.8)';
  if (gameState === 'result') {
    if (result === 'correct') return `0 0 30px rgba(52,211,153,0.15), ${base}`;
    return `0 0 30px rgba(248,113,113,0.1), ${base}`;
  }
  if (mode === 'easy' && proximity === 'close') return `0 0 30px rgba(251,191,36,0.1), ${base}`;
  return base;
}

function getPointerStyle(gameState: GameState, result: Result | null, proximity: Proximity, mode: GameMode) {
  if (gameState === 'result') {
    if (result === 'correct') return { bg: 'linear-gradient(to bottom, #34d399, #065f46)', shadow: '0 0 8px rgba(52,211,153,0.5)' };
    return { bg: 'linear-gradient(to bottom, #f87171, #991b1b)', shadow: '0 0 8px rgba(248,113,113,0.4)' };
  }
  if (mode === 'easy' && proximity === 'close') return { bg: 'linear-gradient(to bottom, #fbbf24, #92400e)', shadow: '0 0 8px rgba(251,191,36,0.4)' };
  return { bg: 'linear-gradient(to bottom, #00d4ff, #0e7490)', shadow: '0 0 8px rgba(0,212,255,0.3)' };
}

function getFreqColor(gameState: GameState, result: Result | null, proximity: Proximity, mode: GameMode) {
  if (gameState === 'result') {
    return result === 'correct' ? 'text-emerald-400' : 'text-red-400';
  }
  if (mode === 'easy' && proximity === 'close') return 'text-amber-400';
  return 'text-white';
}

function getBarGradient(gameState: GameState, result: Result | null, proximity: Proximity, mode: GameMode) {
  if (gameState === 'result') {
    return result === 'correct'
      ? 'linear-gradient(90deg, #065f46, #34d399)'
      : 'linear-gradient(90deg, #991b1b, #f87171)';
  }
  if (mode === 'easy' && proximity === 'close') return 'linear-gradient(90deg, #92400e, #fbbf24)';
  return 'linear-gradient(90deg, #0e7490, #00d4ff)';
}

// ── Pink-noise resonance audio ──────────────────────────────────────
// Pink noise is generated by filtering white noise through a Paul Kellett
// approximation (series of first-order IIR filters), implemented via an
// AudioWorklet processor defined inline as a Blob URL.

const WORKLET_CODE = `
class PinkNoiseProcessor extends AudioWorkletProcessor {
  constructor() {
    super();
    this.b = [0, 0, 0, 0, 0, 0, 0];
  }
  process(inputs, outputs) {
    const out = outputs[0][0];
    if (!out) return true;
    const b = this.b;
    for (let i = 0; i < out.length; i++) {
      const w = Math.random() * 2 - 1;
      b[0] = 0.99886 * b[0] + w * 0.0555179;
      b[1] = 0.99332 * b[1] + w * 0.0750759;
      b[2] = 0.96900 * b[2] + w * 0.1538520;
      b[3] = 0.86650 * b[3] + w * 0.3104856;
      b[4] = 0.55000 * b[4] + w * 0.5329522;
      b[5] = -0.7616 * b[5] - w * 0.0168980;
      out[i] = (b[0] + b[1] + b[2] + b[3] + b[4] + b[5] + b[6] + w * 0.5362) * 0.11;
      b[6] = w * 0.115926;
    }
    return true;
  }
}
registerProcessor('pink-noise', PinkNoiseProcessor);
`;

function useResonanceAudio(targetFreq: number) {
  const [isPlaying, setIsPlaying] = useState(false);
  const ctxRef = useRef<AudioContext | null>(null);
  const noiseRef = useRef<AudioWorkletNode | null>(null);
  const filterRef = useRef<BiquadFilterNode | null>(null);
  const gainRef = useRef<GainNode | null>(null);
  const blobUrlRef = useRef<string | null>(null);

  const stop = useCallback(() => {
    const gain = gainRef.current;
    const ctx = ctxRef.current;
    if (gain && ctx) {
      gain.gain.setTargetAtTime(0, ctx.currentTime, 0.05);
      setTimeout(() => {
        try { noiseRef.current?.disconnect(); } catch {}
        try { filterRef.current?.disconnect(); } catch {}
        try { gain.disconnect(); } catch {}
        noiseRef.current = null;
        filterRef.current = null;
        gainRef.current = null;
      }, 200);
    }
    setIsPlaying(false);
  }, []);

  const play = useCallback(async () => {
    // Tear down any existing playback first
    stop();

    try {
      if (!ctxRef.current || ctxRef.current.state === 'closed') {
        ctxRef.current = new AudioContext();
      }
      const ctx = ctxRef.current;
      if (ctx.state === 'suspended') await ctx.resume();

      if (!blobUrlRef.current) {
        const blob = new Blob([WORKLET_CODE], { type: 'application/javascript' });
        blobUrlRef.current = URL.createObjectURL(blob);
      }
      await ctx.audioWorklet.addModule(blobUrlRef.current).catch(() => {});

      const noise = new AudioWorkletNode(ctx, 'pink-noise');
      const filter = ctx.createBiquadFilter();
      filter.type = 'peaking';
      filter.frequency.value = targetFreq;
      filter.Q.value = 8;        // narrow surgical boost — industry standard resonance hunt Q
      filter.gain.value = 9;     // +9 dB peak — audible but not harsh

      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0, ctx.currentTime);
      gain.gain.setTargetAtTime(0.7, ctx.currentTime, 0.05);

      noise.connect(filter);
      filter.connect(gain);
      gain.connect(ctx.destination);

      noiseRef.current = noise;
      filterRef.current = filter;
      gainRef.current = gain;
      setIsPlaying(true);
    } catch (err) {
      console.error('Audio init failed:', err);
    }
  }, [targetFreq, stop]);

  // Stop playback whenever target changes (new round)
  useEffect(() => {
    stop();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [targetFreq]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      stop();
      if (blobUrlRef.current) {
        URL.revokeObjectURL(blobUrlRef.current);
        blobUrlRef.current = null;
      }
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return { isPlaying, play, stop };
}



export default function App() {
  const { isEarned, refresh: refreshStatus } = useGameStatus();
  const { refreshProfile } = useAuth();
  const [activeMode, setActiveMode] = useState<ActiveMode>('training');

  const [target, setTarget] = useState(() => generateTarget());
  const [freq, setFreq] = useState(1000);
  const [submittedFreq, setSubmittedFreq] = useState<number | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [gameState, setGameState] = useState<GameState>('playing');
  const [gameMode, setGameMode] = useState<GameMode>('easy');
  const [pointsEarned, setPointsEarned] = useState<number | null>(null);
  const [isAwarding, setIsAwarding] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [currentRound, setCurrentRound] = useState(1);
  const [history, setHistory] = useState<RoundRecord[]>([]);
  const dragStartY = useRef(0);
  const dragStartAngle = useRef(0);
  const { isPlaying, play, stop } = useResonanceAudio(target);

  const angle = freqToAngle(freq);
  const proximity = getProximity(freq, target);
  const isKnobLocked = gameState !== 'playing';
  const displayFreq = gameState === 'result' && submittedFreq !== null ? submittedFreq : freq;
  const diffDisplay = gameState === 'result' && submittedFreq !== null ? Math.abs(submittedFreq - target) : null;
  const pointerStyle = getPointerStyle(gameState, result, proximity, gameMode);
  const wins = history.filter((r) => r.correct).length;

  const handleSubmit = useCallback(() => {
    if (gameState !== 'playing') return;
    const res = getResult(freq, target);
    const diff = Math.abs(freq - target);
    setSubmittedFreq(freq);
    setResult(res);
    setHistory((h) => [...h, { diff, correct: res === 'correct' }]);
    if (currentRound >= TOTAL_ROUNDS) {
      setGameState('session_end');
    } else {
      setGameState('result');
    }
  }, [freq, target, gameState, currentRound]);

  const handleNextRound = useCallback(() => {
    setTarget(generateTarget());
    setFreq(1000);
    setSubmittedFreq(null);
    setResult(null);
    setCurrentRound((r) => r + 1);
    setGameState('playing');
  }, []);

  const handleRestartSession = useCallback(() => {
    setTarget(generateTarget());
    setFreq(1000);
    setSubmittedFreq(null);
    setResult(null);
    setCurrentRound(1);
    setHistory([]);
    setGameState('playing');
  }, []);

  const handleModeToggle = useCallback(() => {
    if (gameState !== 'playing') return;
    setGameMode((m) => (m === 'easy' ? 'hard' : 'easy'));
  }, [gameState]);

  const onPointerDown = useCallback(
    (e: React.PointerEvent) => {
      if (isKnobLocked) return;
      e.preventDefault();
      setIsDragging(true);
      dragStartY.current = e.clientY;
      dragStartAngle.current = freqToAngle(freq);
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
    },
    [freq, isKnobLocked],
  );

  const onPointerMove = useCallback(
    (e: React.PointerEvent) => {
      if (!isDragging || isKnobLocked) return;
      const deltaY = dragStartY.current - e.clientY;
      const newAngle = clamp(dragStartAngle.current + deltaY * 0.5, ANGLE_MIN, ANGLE_MAX);
      setFreq(angleToFreq(newAngle));
    },
    [isDragging, isKnobLocked],
  );

  const onPointerUp = useCallback(() => setIsDragging(false), []);

  const tickMarks = [];
  for (let i = 0; i <= 20; i++) {
    const tickAngle = ANGLE_MIN + (i / 20) * (ANGLE_MAX - ANGLE_MIN);
    const tickFreq = angleToFreq(tickAngle);
    tickMarks.push({ angle: tickAngle, active: tickFreq <= displayFreq });
  }

  // ── Mode navigation (fixed overlay — does not affect Training layout) ──
  const today = getTodayKey();
  const easyDone = isEarned('ear-training', `easy:${today}`);
  const hardDone = isEarned('ear-training', `hard:${today}`);
  const ModeNav = (
    <div className="flex flex-col items-center gap-2 mb-4">
      <div className="flex gap-0 bg-[#111] border border-gray-800/60 rounded-lg overflow-hidden pointer-events-auto">
        <button
          onClick={() => setActiveMode('training')}
          className={`px-5 py-1.5 text-[10px] tracking-[0.2em] uppercase font-medium transition-all duration-150 ${
            activeMode === 'training'
              ? 'text-cyan-300 bg-cyan-950/40 border-r border-gray-800/60'
              : 'text-gray-600 hover:text-gray-400 border-r border-gray-800/60'
          }`}
        >
          Training
        </button>
        <button
          onClick={() => setActiveMode('lab')}
          className={`px-5 py-1.5 text-[10px] tracking-[0.2em] uppercase font-medium transition-all duration-150 ${
            activeMode === 'lab'
              ? 'text-amber-300 bg-amber-950/30'
              : 'text-gray-600 hover:text-gray-400'
          }`}
        >
          Lab
        </button>
      </div>
      {activeMode === 'training' && (
        <div className="flex items-center gap-3 text-[10px] font-bold">
          <span style={{ color: easyDone ? '#475569' : '#34d399' }}>
            {easyDone ? '✓ Easy 완료' : <><span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse mr-1" />Easy 1점 가능</>}
          </span>
          <span className="text-slate-700">|</span>
          <span style={{ color: hardDone ? '#475569' : '#f59e0b' }}>
            {hardDone ? '✓ Hard 완료' : <><span className="inline-block w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse mr-1" />Hard 3점 가능</>}
          </span>
          <span className="text-slate-700">·</span>
          <span className="text-slate-600">{fmtCountdownDaily()}</span>
        </div>
      )}
    </div>
  );

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => {
    if (gameState !== 'session_end') return;
    const wins = history.filter(r => r.correct).length;
    const accuracy = Math.round((wins / TOTAL_ROUNDS) * 100);
    if (accuracy < 70) return;
    setIsAwarding(true);
    awardEarTrainingPoints(gameMode).then(pts => {
      setIsAwarding(false);
      if (pts > 0) { setPointsEarned(pts); refreshStatus(); refreshProfile(); }
    });
  }, [gameState]);

  if (activeMode === 'lab') {
    return (
      <>
        {ModeNav}
        <LabMode />
      </>
    );
  }

  // ── Session End Screen ──────────────────────────────────────────────
  if (gameState === 'session_end') {
    const totalWins = [...history].filter((r) => r.correct).length;
    const avgError =
      history.length > 0
        ? Math.round(history.reduce((sum, r) => sum + r.diff, 0) / history.length)
        : 0;
    const accuracy = Math.round((totalWins / TOTAL_ROUNDS) * 100);

    return (
      <>
        {ModeNav}
        <div className="relative bg-[#0d0d0d] flex flex-col items-center justify-center select-none overflow-hidden">
        <VaultBackground />
        <div className="relative z-10 flex flex-col items-center gap-8 px-6 text-center max-w-sm w-full">
          <div>
            <p className="text-xs tracking-[0.3em] text-gray-600 uppercase mb-2">Session Complete</p>
            <h2 className="text-4xl font-light text-white">
              {totalWins} <span className="text-gray-600 text-2xl">/ {TOTAL_ROUNDS}</span>
            </h2>
            <p className="text-sm text-gray-500 mt-1">rounds correct</p>
          </div>

          <div className="w-full grid grid-cols-2 gap-3">
            <div className="bg-[#141414] border border-gray-800/60 rounded-lg p-4">
              <p className="text-[10px] tracking-widest text-gray-600 uppercase mb-1">Accuracy</p>
              <p
                className={`text-2xl font-light tabular-nums ${
                  accuracy >= 70 ? 'text-emerald-400' : accuracy >= 40 ? 'text-amber-400' : 'text-red-400'
                }`}
              >
                {accuracy}%
              </p>
            </div>
            <div className="bg-[#141414] border border-gray-800/60 rounded-lg p-4">
              <p className="text-[10px] tracking-widest text-gray-600 uppercase mb-1">Avg Error</p>
              <p className="text-2xl font-light tabular-nums text-white">
                {avgError} <span className="text-sm text-gray-500">Hz</span>
              </p>
            </div>
          </div>

          <div className="w-full bg-[#141414] border border-gray-800/60 rounded-lg p-4">
            <p className="text-[10px] tracking-widest text-gray-600 uppercase mb-3">Round Breakdown</p>
            <div className="flex gap-1.5 justify-center flex-wrap">
              {history.map((r, i) => (
                <div
                  key={i}
                  className={`w-7 h-7 rounded flex items-center justify-center text-[10px] font-medium ${
                    r.correct
                      ? 'bg-emerald-950/60 text-emerald-400 border border-emerald-800/40'
                      : 'bg-red-950/40 text-red-400 border border-red-900/40'
                  }`}
                  title={`Round ${i + 1}: off by ${r.diff} Hz`}
                >
                  {i + 1}
                </div>
              ))}
            </div>
          </div>

          {isAwarding && (
            <div className="px-5 py-2.5 rounded-xl text-sm font-bold" style={{ background: 'rgba(0,229,255,0.05)', border: '1px solid rgba(0,229,255,0.15)', color: '#64748b' }}>
              채점 및 포인트 서버 기록 중...
            </div>
          )}
          {!isAwarding && pointsEarned !== null && (
            <div className="px-5 py-2.5 rounded-xl text-sm font-bold" style={{ background: 'rgba(0,229,255,0.1)', border: '1px solid rgba(0,229,255,0.25)', color: '#67e8f9' }}>
              +{pointsEarned}점 획득!
            </div>
          )}
          <button
            onClick={() => { setPointsEarned(null); handleRestartSession(); }}
            className="px-8 py-3 text-sm tracking-[0.2em] uppercase font-semibold rounded transition-all duration-200 text-cyan-300 bg-[#0e2a33] border border-cyan-800/50 hover:bg-[#133d4a] hover:text-cyan-200 hover:border-cyan-700/60"
          >
            Restart Session
          </button>
        </div>
      </div>
      </>
    );
  }

  // ── Game Screen ─────────────────────────────────────────────────────
// ── Game Screen (App.tsx) ───────────────────────────────────────────
  return (
    <>
      {ModeNav}
      
      {/* 교정됨: bg-[#050505] 및 min-h-screen 속성 제거 (웹사이트 원래 배경 투과) */}
      <div className="w-full flex justify-center py-6 px-2">
        
        {/* === 독립된 하드웨어 패널 본체 === */}
        <div 
          className="relative w-full max-w-[460px] bg-[#0a0a0a] rounded-2xl flex flex-col items-center select-none pb-12 overflow-hidden"
          style={{
            border: '1px solid #151515',
            borderTop: '1px solid #2f2f2f',
            borderBottom: '1px solid #000',
            boxShadow: '0 40px 80px rgba(0,0,0,1), inset 0 1px 0 rgba(255,255,255,0.03), inset 15px 0 40px rgba(0,0,0,0.6), inset -15px 0 40px rgba(0,0,0,0.6)'
          }}
        >
          {/* 네 모서리 고정 나사못 */}
          <div className="absolute top-5 left-5 w-2 h-2 rounded-full bg-[#050505] border border-[#222] shadow-[inset_0_1px_2px_rgba(0,0,0,1)]" />
          <div className="absolute top-5 right-5 w-2 h-2 rounded-full bg-[#050505] border border-[#222] shadow-[inset_0_1px_2px_rgba(0,0,0,1)]" />
          <div className="absolute bottom-5 left-5 w-2 h-2 rounded-full bg-[#050505] border border-[#222] shadow-[inset_0_1px_2px_rgba(0,0,0,1)]" />
          <div className="absolute bottom-5 right-5 w-2 h-2 rounded-full bg-[#050505] border border-[#222] shadow-[inset_0_1px_2px_rgba(0,0,0,1)]" />

          {/* 상단 통풍구/LED 가이드라인 장식 (청록색 계열로 변경) */}
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-cyan-900/30 to-transparent" />
          <div className="absolute top-4 left-1/2 -translate-x-1/2 flex gap-1.5 opacity-30">
            <div className="w-4 h-0.5 bg-cyan-600 rounded-full" />
            <div className="w-4 h-0.5 bg-cyan-600 rounded-full" />
            <div className="w-4 h-0.5 bg-cyan-600 rounded-full" />
          </div>

          <div className="relative z-10 flex flex-col items-center w-full pt-14 px-5 gap-6">

            {/* Header row: round counter + mode toggle */}
            <div className="flex items-center justify-between w-full">
              <span className="text-xs text-gray-600 tabular-nums">
                Round <span className="text-gray-400 font-medium">{currentRound}</span> / {TOTAL_ROUNDS}
              </span>
              <button
                onClick={handleModeToggle}
                disabled={gameState !== 'playing'}
                className={`px-3 py-1 text-xs tracking-[0.15em] uppercase font-medium rounded transition-all duration-200 border ${
                  gameMode === 'easy'
                    ? 'text-cyan-400 bg-cyan-950/30 border-cyan-800/40'
                    : 'text-gray-500 bg-[#141414] border-gray-800/40'
                } ${gameState !== 'playing' ? 'opacity-40 cursor-default' : 'hover:opacity-80'}`}
              >
                {gameMode === 'easy' ? 'Easy' : 'Hard'}
              </button>
            </div>

            {/* Target reveal */}
            <div className="flex flex-col items-center gap-1 w-full text-center">
              <span className="text-xs tracking-[0.2em] text-gray-600 uppercase">Target Frequency</span>
              <div className="h-10 flex items-center justify-center">
                {gameState === 'result' ? (
                  <span className="text-3xl font-light text-cyan-400 tabular-nums tracking-wider drop-shadow-[0_0_12px_rgba(34,211,238,0.3)]">
                    {target.toLocaleString()} Hz
                  </span>
                ) : (
                  <span className="text-3xl font-light text-cyan-400/30 tracking-widest">???</span>
                )}
              </div>
            </div>

            {/* Status / hint indicator */}
            <div className="flex flex-col items-center gap-1 min-h-[48px] justify-center text-center">
              {gameState === 'result' && result ? (
                <>
<span
                    className={`text-2xl font-bold tracking-[0.25em] transition-all duration-300 ${
                      result === 'correct'
                        ? 'text-emerald-400 drop-shadow-[0_0_12px_rgba(52,211,153,0.6)]'
                        : 'text-red-400 drop-shadow-[0_0_8px_rgba(248,113,113,0.5)]'
                    }`}
                  >
                    {result === 'correct' ? 'UNLOCKED' : 'INCORRECT'}
                  </span>
                  <span className="text-sm text-gray-500">
                    {result === 'correct' ? `Within ±${TOLERANCE_PCT}%` : `Off by ${diffDisplay} Hz`}
                  </span>
                </>
              ) : gameMode === 'easy' ? (
                <>
                  <span
                    className={`text-2xl font-bold tracking-[0.25em] transition-all duration-300 ${
                      proximity === 'close'
                        ? 'text-amber-400 drop-shadow-[0_0_8px_rgba(251,191,36,0.5)]'
                        : 'text-gray-500'
                    }`}
                  >
                    {proximity === 'close' ? 'CLOSE' : 'FAR'}
                  </span>
                  <span className="text-sm text-gray-600">
                    {proximity === 'close' ? 'Almost there...' : 'Keep searching...'}
                  </span>
                </>
              ) : (
                <span className="text-[11px] text-gray-500 tracking-widest uppercase">Submit to evaluate</span>
              )}
            </div>

            {/* === 입체 다이얼 케이싱 === */}
            <div className="relative flex items-center justify-center my-4">
              <div 
                className="relative flex items-center justify-center rounded-full"
                style={{
                  width: '320px',
                  height: '320px',
                  background: 'conic-gradient(from 180deg at 50% 50%, #151515 0%, #2a2a2a 20%, #0d0d0d 50%, #2a2a2a 80%, #151515 100%)',
                  boxShadow: '0 20px 50px rgba(0,0,0,0.9), inset 0 2px 2px rgba(255,255,255,0.05)',
                  border: '1px solid #000'
                }}
              >
                <div 
                  className="absolute inset-[14px] rounded-full flex items-center justify-center"
                  style={{
                    background: '#0a0a0a',
                    boxShadow: 'inset 0 10px 40px rgba(0,0,0,1), 0 1px 1px rgba(255,255,255,0.08)',
                    border: '1px solid #000'
                  }}
                >
                  <svg className="absolute inset-0 w-full h-full opacity-60 pointer-events-none" viewBox="0 0 290 290">
                    <circle cx="145" cy="145" r="135" fill="none" stroke="#141414" strokeWidth="2" />
                    {Array.from({ length: 6 }).map((_, i) => {
                      const angle = (i * 60) * (Math.PI / 180);
                      return (
                        <circle
                          key={`bolt-${i}`}
                          cx={145 + Math.cos(angle) * 126} cy={145 + Math.sin(angle) * 126}
                          r="3.5" fill="#050505" stroke="#222" strokeWidth="1"
                        />
                      );
                    })}
                  </svg>

                  {/* 눈금자 */}
                  <svg className="absolute z-10" width="220" height="220" viewBox="-110 -110 220 220">
                    {tickMarks.map((tick, i) => {
                      const rad = (tick.angle - 90) * (Math.PI / 180);
                      const r1 = 95;
                      const r2 = tick.active ? 82 : 86;
                      return (
                        <line
                          key={i}
                          x1={Math.cos(rad) * r1} y1={Math.sin(rad) * r1}
                          x2={Math.cos(rad) * r2} y2={Math.sin(rad) * r2}
                          stroke={tick.active ? 'rgba(0,212,255,0.6)' : 'rgba(255,255,255,0.12)'}
                          strokeWidth={tick.active ? 2 : 1}
                          strokeLinecap="round"
                        />
                      );
                    })}
                  </svg>

                  {/* 노브 본체 */}
                  <div
                    onPointerDown={onPointerDown}
                    onPointerMove={onPointerMove}
                    onPointerUp={onPointerUp}
                    onPointerCancel={onPointerUp}
                    className={`relative z-20 w-36 h-36 rounded-full touch-none ${
                      isKnobLocked ? 'cursor-default' : 'cursor-grab active:cursor-grabbing'
                    }`}
                    style={{
                      background: 'radial-gradient(circle at 40% 35%, #2a2a2a 0%, #1a1a1a 50%, #0d0d0d 100%)',
                      boxShadow: getKnobShadow(gameState, result, proximity, gameMode),
                    }}
                  >
                    <div className="absolute inset-2 rounded-full" style={{ border: '1px solid rgba(255,255,255,0.04)' }} />
                    <div className="absolute inset-0" style={{ transform: `rotate(${angle}deg)` }}>
                      <div
                        className="absolute left-1/2 top-3 -translate-x-1/2 w-1 h-8 rounded-full"
                        style={{ background: pointerStyle.bg, boxShadow: pointerStyle.shadow }}
                      />
                    </div>
                    <div
                      className="absolute inset-[46px] rounded-full"
                      style={{ background: 'radial-gradient(circle at 40% 35%, #333, #151515)', border: '1px solid rgba(255,255,255,0.05)' }}
                    />
                  </div>
                </div>
              </div>
            </div>

            <p className="text-[10px] text-gray-700 tracking-[0.2em] uppercase">
              {isKnobLocked ? 'Frequency locked' : isDragging ? 'Adjusting...' : 'Drag knob to adjust'}
            </p>

            {/* Frequency display */}
            <div className="flex flex-col items-center gap-1 w-full">
              <div className="flex items-baseline gap-1">
                <span
                  className={`text-5xl font-extralight tabular-nums tracking-wider transition-colors duration-300 ${getFreqColor(gameState, result, proximity, gameMode)}`}
                >
                  {displayFreq.toLocaleString()}
                </span>
                <span className="text-lg text-gray-500 font-light">Hz</span>
              </div>

              <div className="w-64 h-1 bg-[#1a1a1a] rounded-full mt-2 overflow-hidden shadow-[inset_0_1px_2px_rgba(0,0,0,0.5)]">
                <div
                  className="h-full rounded-full transition-all duration-75"
                  style={{
                    width: `${((displayFreq - FREQ_MIN) / (FREQ_MAX - FREQ_MIN)) * 100}%`,
                    background: getBarGradient(gameState, result, proximity, gameMode),
                  }}
                />
              </div>

              <div className="flex justify-between w-64 text-[10px] text-gray-700 mt-1">
                <span>{FREQ_MIN} Hz</span>
                <span>{FREQ_MAX} Hz</span>
              </div>

              <p className="text-[10px] text-gray-700 tracking-widest mt-1">
                Tolerance: ±{TOLERANCE_PCT}%
              </p>
            </div>

            {/* Controls */}
            <div className="flex gap-3 mt-2 items-center">
              {gameState !== 'session_end' && (
                <>
                  <button
                    onClick={play}
                    disabled={isPlaying}
                    className={`px-5 py-2.5 text-xs tracking-[0.15em] uppercase font-medium rounded transition-all duration-200 border ${
                      isPlaying
                        ? 'text-gray-600 bg-[#111] border-gray-900/60 cursor-default'
                        : 'text-gray-300 bg-[#151515] border-gray-700/50 hover:bg-[#222] hover:text-white hover:border-gray-600/60 shadow-lg'
                    }`}
                  >
                    Play
                  </button>
                  <button
                    onClick={stop}
                    disabled={!isPlaying}
                    className={`px-5 py-2.5 text-xs tracking-[0.15em] uppercase font-medium rounded transition-all duration-200 border ${
                      !isPlaying
                        ? 'text-gray-700 bg-[#111] border-gray-900/60 cursor-default'
                        : 'text-gray-300 bg-[#151515] border-gray-700/50 hover:bg-[#222] hover:text-white hover:border-gray-600/60 shadow-lg'
                    }`}
                  >
                    Stop
                  </button>
                  <div className="w-px h-5 bg-gray-800/60 mx-1" />
                </>
              )}
              {gameState === 'playing' && (
                <>
                  <button
                    onClick={handleSubmit}
                    className="px-8 py-2.5 text-sm tracking-[0.2em] uppercase font-semibold rounded transition-all duration-200 text-cyan-300 bg-[#0e2a33] border border-cyan-800/50 hover:bg-[#133d4a] hover:text-cyan-200 hover:border-cyan-700/60 shadow-[0_0_15px_rgba(34,211,238,0.1)]"
                  >
                    Submit
                  </button>
                 
                </>
              )}
              {gameState === 'result' && (
                <button
                  onClick={handleNextRound}
                  className="px-8 py-2.5 text-sm tracking-[0.2em] uppercase font-semibold rounded transition-all duration-200 text-cyan-300 bg-[#0e2a33] border border-cyan-800/50 hover:bg-[#133d4a] hover:text-cyan-200 hover:border-cyan-700/60 shadow-[0_0_15px_rgba(34,211,238,0.1)]"
                >
                  {currentRound >= TOTAL_ROUNDS ? 'See Results' : 'Next Round'}
                </button>
              )}
            </div>

            {/* Score footer */}
            <p className="text-[10px] text-gray-700 tabular-nums uppercase tracking-widest mt-2">
              {wins} correct so far
            </p>
            
          </div>
        </div>
      </div>
    </>
  );
}